/*********************************************************************************
Project: BEP

Purpose: Baseline area business survey data treatment of open-ended text fields 

Author:  Azhar Hussain

Date  :  28 April, 2015
**********************************************************************************/



* PUSHING DATA IN "OTHERS" CATEGORY TO EXISTING CATEGORIES OR GENERATING NEW CATEGORIES IF THEY DON'T BELONG TO ANY EXISTING ONES

	//// Section - 0 [General Information]
	
	//// Section - A [Information about business premises]
	//a1_proprietor_oth
	replace a1_proprietor = 3 if a1_proprietor_oth == "Compounder hai."
	replace a1_proprietor = 3 if a1_proprietor_oth == "Kamgar"
	replace a1_proprietor = 3 if a1_proprietor_oth == "Karigar"
	replace a1_proprietor = 3 if a1_proprietor_oth == "Kiraya par hai"
	replace a1_proprietor = 3 if a1_proprietor_oth == "Mai yaha ka pure manejmet karte hai"
	replace a1_proprietor = 3 if a1_proprietor_oth == "Sels man hai yani naukar hai ."
	replace a1_proprietor = 2 if a1_proprietor_oth == "Pariwar se"

	//a4_owner_oth
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Road ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi deta p. W.d.me dukan rakha"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jamin  hai."
	replace a4_owner = 3 if a4_owner_oth == "Pwd jmeen"
	replace a4_owner = 3 if a4_owner_oth == "P.w.d. ke jamen par gumti rakha hai kiraya nhi padta hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi dete hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi barte hai service"
	replace a4_owner = 3 if a4_owner_oth == "School  ka  jamin  hai."
	replace a4_owner = 2 if a4_owner_oth == "Pahchan  ka  admi  hai."
	replace a4_owner = 3 if a4_owner_oth == "P. W .d ki jamen me dukan hai iska kiraya nahi deta hai"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jameen  hai."
	replace a4_owner = 3 if a4_owner_oth == "Dukan ke kiraya nhi data hai  hotal ke jagha me kam karta hai"
	replace a4_owner = 3 if a4_owner_oth == "P.w.d ke jagha me dukan hai iska kiraya nahi deta hai"
	replace a4_owner = 3 if a4_owner_oth == "Bihar government"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jamin  hai."
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jamin  hai."
	replace a4_owner = 3 if a4_owner_oth == "Pwd ke jamen par gumti rakha hai kiraya nhi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ke jamen par gumti rakha hai kiraya nhi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jamin  hai"
	replace a4_owner = 3 if a4_owner_oth == "Road  par  jamin  hai."
	replace a4_owner = 3 if a4_owner_oth == "Pwd ke jamen par dukan hai iska kiraya nahi deta hai"
	replace a4_owner = 2 if a4_owner_oth == "Pahchan  ka  hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi deta P.w.d ke jagha me dukan hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi dete hai bihar sarakar ka jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi padta hai"
	replace a4_owner = 3 if a4_owner_oth == "Govement ka"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Jamin sarkari hai kiraya nahi padata hai"
	replace a4_owner = 3 if a4_owner_oth == "Nahar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Ghar keb samne hai pwd ka zameen hai"
	replace a4_owner = 2 if a4_owner_oth == "Priwar ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Rood  ki dukan"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin me gumti hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin me gumti  hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  government"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 2 if a4_owner_oth == "Ye jameen ka kiraya nahi padta hai relationship hone ke karan"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Gaverment ki hai"
	replace a4_owner = 3 if a4_owner_oth == "Jagah sarkari hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Lakri ki gumti"
	replace a4_owner = 3 if a4_owner_oth == "Yahan par kiraya nahi parta"
	replace a4_owner = 3 if a4_owner_oth == "P.w. d"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Jamin sarkari hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen  pr"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ke jamen par gumti rakha hai kiraya nhi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai kiraya nahi bharte hai"
	replace a4_owner = 3 if a4_owner_oth == "Bihar  sarkar  ka  jamin  hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi padta hai"
	replace a4_owner = 2 if a4_owner_oth == "Ye jameen dost ka hai kiraya nahi  bharte"
	replace a4_owner = 3 if a4_owner_oth == "Garmajruwa land"
	replace a4_owner = 3 if a4_owner_oth == "Jamin keraya nahi lagata hi yah jamin sakari hi"
	replace a4_owner = 3 if a4_owner_oth == "Yha shop sakari hi ishaka kiraya nahi lagata hi"
	replace a4_owner = 3 if a4_owner_oth == "Yha shop ki jamin shakari hi ishaka kirya nahi lagata hi"
	replace a4_owner = 3 if a4_owner_oth == "Yha jamin sakari hi ishaka kiraya nahi lagata hi"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Yha jamin sarkari hi ishaka kiraya nahi lagata hi"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari land"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari land"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pdw"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi pdta hai"
	replace a4_owner = 3 if a4_owner_oth == "Withaut rent"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari sampati hai"
	replace a4_owner = 3 if a4_owner_oth == "Ye government land hai"
	replace a4_owner = 3 if a4_owner_oth == "P w d ke jamen me dukan  hai kiraya nhi date hai"
	replace a4_owner = 3 if a4_owner_oth == "Gram panchayat ki jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Gaorment ki jameen."
	replace a4_owner = 3 if a4_owner_oth == "Railway ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Railway ki jamin"
	replace a4_owner = 3 if a4_owner_oth == "Yha jamin railway ki hi ishska kiraya nahih lagata hi"
	replace a4_owner = 3 if a4_owner_oth == "Railway ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Railway ki jamin"
	replace a4_owner = 3 if a4_owner_oth == "Jamin school ki hai kiraya nahi dete hai"
	replace a4_owner = 3 if a4_owner_oth == "Ye Jameen school ki hai"
	replace a4_owner = 2 if a4_owner_oth == "Dusre ki jamin hay kiraya nahi dete hay"
	replace a4_owner = 2 if a4_owner_oth == "Jameen dost ka hai paise nahi dete hain"
	replace a4_owner = 3 if a4_owner_oth == "ROAD KA JAMEEN HAI KIRAYA NAHI LAGTA HAI."
	replace a4_owner = 2 if a4_owner_oth == "Kiraya nahi padta family ki jameen hai"
	replace a4_owner = 3 if a4_owner_oth == "P. W. D."
	replace a4_owner = 3 if a4_owner_oth == "Goverment plot"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi dete h"
	replace a4_owner = 3 if a4_owner_oth == "Jameen sarkari hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jameen h"
	replace a4_owner = 3 if a4_owner_oth == "Jameen sarkari hai"
	replace a4_owner = 3 if a4_owner_oth == "Ye govt jameen pe hai"
	replace a4_owner = 3 if a4_owner_oth == "P w d ke jamen me dukan hai kiray nahi date"
	replace a4_owner = 3 if a4_owner_oth == "P W D ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jgah pr"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "P w d  ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai is liye kiraya nahi dete hain"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen pr hai"
	replace a4_owner = 3 if a4_owner_oth == "Jamin bihar sarkar ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Bihar sarkar ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen hai esliye kiraya nahi bharte hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai kiraya nahi lagta hai."
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi dete h"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Kirya nahi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Gaverment ka"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki zameen hai kiraya nahi bharte hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Bata nhi sakte"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ki jmeen hai"
	replace a4_owner = 2 if a4_owner_oth == "Shop dusri shop ke smane hai partnership me kiraya nahi bharte hai."
	replace a4_owner = 3 if a4_owner_oth == "Kiraya koi nhi par mele k samy sal me  3000 rupya  chanda rup me jameen ka dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Voda fone kampani"
	replace a4_owner = 3 if a4_owner_oth == "Gaverment ki"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai."
	replace a4_owner = 3 if a4_owner_oth == "Sakari zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Mandir ka jameen hai"
	replace a4_owner = 2 if a4_owner_oth == "Dukan respondent ka dost ka hai kiraya nahi lagta"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi padta"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jagh he"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen"
	replace a4_owner = 3 if a4_owner_oth == "Khokha me dukan sadak ke kinare"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya padta nahi"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka h"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamipar dukan gumti me rakhi hai"
	replace a4_owner = 3 if a4_owner_oth == "Keraya nahi padta hai"
	replace a4_owner = 3 if a4_owner_oth == "Gumti"
	replace a4_owner = 3 if a4_owner_oth == "Jamin sarkari h"
	replace a4_owner = 3 if a4_owner_oth == "Gumti"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen par apni dukan rakhe huye koi kiraya nahi bharte hai"
	replace a4_owner = 3 if a4_owner_oth == "P.w.d ki jameen me dukan hai kiraya nahi dena padata hai"
	replace a4_owner = 3 if a4_owner_oth == "Municipalti ki jameen par karo bar kar rahe hain"
	replace a4_owner = 3 if a4_owner_oth == "Khokhe ki dukan"
	replace a4_owner = 3 if a4_owner_oth == "Gumti"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zammen par gumti lagye hue hain"
	replace a4_owner = 3 if a4_owner_oth == "Lakdi ki dukan hai kiraya nahi dete hain"
	replace a4_owner = 2 if a4_owner_oth == "Mitr kiraya Bharat hai."
	replace a4_owner = 3 if a4_owner_oth == "Darbhanga mahraj ki jameen hai."
	replace a4_owner = 3 if a4_owner_oth == "Darbhanga mahraj ki jameen hai."
	replace a4_owner = 3 if a4_owner_oth == "Darbhanga mahraj ki jameen hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari hai"
	replace a4_owner = 1 if a4_owner_oth == "Malikana zameen hai kiraya nahi bharte"
	replace a4_owner = 1 if a4_owner_oth == "Malikana zameen hai kiraya nahi bharte hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "P w d ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Roed said"
	replace a4_owner = 3 if a4_owner_oth == "Gumti p w d  ke jamen me hai kiry nahi data hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Mandir ki zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd  ki jmeen pr hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd mjeen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd jmeen"
	replace a4_owner = 3 if a4_owner_oth == "Road  ka  jamin  hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd jmeen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "P.w.d ka jameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka nai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ke jamen me dukan hai kiray nahi date hai"
	replace a4_owner = 3 if a4_owner_oth == "P W D ki jamen , me dukan rkai hai kirya nahi date hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka zameen hai"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Relway ki jamin m dukan rakhi h, isliye kiraya nhi padta h"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai iska koi kiraya nahi dena padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Yatri sed me dukan hai"
	replace a4_owner = 2 if a4_owner_oth == "Dusare ka jamin par"
	replace a4_owner = 2 if a4_owner_oth == "Bhai ka makan hai kiraya nahi dete hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin"
	replace a4_owner = 3 if a4_owner_oth == "Gandhi hotal ka jamin hai kiraya nahi dete hai"
	replace a4_owner = 3 if a4_owner_oth == "Gomti sarkari jamin par"
	replace a4_owner = 3 if a4_owner_oth == "Gomti sarkari jamin par hai"
	replace a4_owner = 2 if a4_owner_oth == "Ye jamin ka kiraya nahi lagta hai.ye inke relative ka jamin hai."
	replace a4_owner = 3 if a4_owner_oth == "Shrkari"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari land hai"
	replace a4_owner = 3 if a4_owner_oth == "Gumti han iska kiraya nahi dete han"
	replace a4_owner = 3 if a4_owner_oth == "PWD ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi dete hai (gumti)"
	replace a4_owner = 3 if a4_owner_oth == "Gungti mera hai lekin jagah sarkari hai."
	replace a4_owner = 3 if a4_owner_oth == "Parisar sarkar ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Yah jamin sarkar ka han"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi dete"
	replace a4_owner = 3 if a4_owner_oth == "Railway line"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 2 if a4_owner_oth == "Kiraya nayhe data hai ya appna vi nahay hai dusaray say la kar Kea hai dukan dari Kea hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai jiska koi raint nahi lagta hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Government ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai jiska koi raint nahi lagta hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Pwd"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi lagta hai rod par dukan"
	replace a4_owner = 3 if a4_owner_oth == "Government ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Government ka hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Gorment ka hai.rent nahi lagta hai."
	replace a4_owner = 3 if a4_owner_oth == "Jamin sarkar ki hi"
	replace a4_owner = 3 if a4_owner_oth == "Pwd ka hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi padta hai."
	replace a4_owner = 3 if a4_owner_oth == "Apana nahi hai aur kiraya bhi nahi lagrta"
	replace a4_owner = 3 if a4_owner_oth == "Gorment ki jamin hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Government jamin"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari land hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari pariwar hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ke jamin par shop hai."
	replace a4_owner = 3 if a4_owner_oth == "P.w.d ka jameen hai kiraya nahi padta hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nhi dete"
	replace a4_owner = 3 if a4_owner_oth == "Goverment ploit"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Govrment"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Goverment ploit"
	replace a4_owner = 3 if a4_owner_oth == "Kiraya nahi dete hai relbe ka jagah hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkar ki jagah"
	replace a4_owner = 3 if a4_owner_oth == "Road  ka  jamin  hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jameen me apna gumti hai koi kiraya nahi lagta"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin par kiraye nahi dete hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jagh me dukan hai"
	replace a4_owner = 3 if a4_owner_oth == "Goverment"
	replace a4_owner = 3 if a4_owner_oth == "Road ke bgal me shop hai. Is liye kiraya nhi lagta hai.."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin par hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin par dukan hai, lekin karobar mera hai."
	replace a4_owner = 3 if a4_owner_oth == "Railwey ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Railwey ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Ralwey ka jamin hai"
	replace a4_owner = 3 if a4_owner_oth == "Lakri ka gumti(katra)rod ke bagal mai"
	replace a4_owner = 3 if a4_owner_oth == "Dukaan sarkari palace par hai jiska koi kiraya nahi date hain"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari"
	replace a4_owner = 3 if a4_owner_oth == "Gomti kiraya par"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari plat hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin me shop chalta hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari makan me shop chalta hai"
	replace a4_owner = 3 if a4_owner_oth == "Koi kiraya nahi lagta"
	replace a4_owner = 1 if a4_owner_oth == "Kam ke malik ka gar he"
	replace a4_owner = 3 if a4_owner_oth == "Dukan  relway line ki jameen par hai"
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin par hai."
	replace a4_owner = 3 if a4_owner_oth == "Sarkari jamin par hai."
	replace a4_owner = 3 if a4_owner_oth == "Kirya nhi date p w d ke jamin me dukan hai"
	replace a4_owner = 2 if a4_owner_oth == "Sathi ka jagah hai"


	
	//// Section - B [Information about employees]

	
	//// Section - C [Information about physical assets owned by the business]

	
	//// Section - D [Information about inventory maintained by the business]

	
	//// Section - E [Information about energy consumption by the business]

	
	//// Section - F [Information about electricity supply situation]

	
	//// Section - G [Information about expenditure, revenue and credit of the business]

	
	//// Section - H [Interviewer’s Notes]

