/*******************************************************************************
Project: BEP

Purpose: Basic cleaning of sampled village distribution transformer survey data

Author:  Azhar Hussain

Date  :  17 June, 2015
********************************************************************************/



* OPENING COMMANDS:

	clear
	set more off
	pause on
	version 12.0
	cap log close
	

* AUTOMATED SELECTION OF ROOT PATH BASED ON USER

	if c(os) == "Windows" {
		cd "C:/Users/`c(username)'/Dropbox"
	}
	else if c(os) == "MacOSX" {
		cd "/Users/`c(username)'/Dropbox"
	}
	local DROPBOX `c(pwd)'
	if "`c(username)'" == "nryan" {
	local DROPBOX_ROOT "`DROPBOX'/distribution"
	}
	else {
	local DROPBOX_ROOT "`DROPBOX'/Bihar Electrification Project"
	}

	
* SETTING PATH SHORTCUTS

	local RAW_DATA  "`DROPBOX_ROOT'/Data/Survey/Baseline/Raw Data"
	local WORKING_DATA  "`DROPBOX_ROOT'/Data/Survey/Baseline/Working Data"


* MERGING AREA TYPE AND LOADING RAW DATA IN MEMORY

	cd "`RAW_DATA'"
	insheet using "Area_Type.csv", n
	split areaid, p(-) generate(village_id)
	destring village_id*, replace
	merge 1:m district pss feeder area using CUMULATIVE_DT_VIL_16May2015
	//Dropping villages that have remained unelectrified historically
	drop if _merge==1

* PERFORMING BASIC CLEANING
	
	// Dropping insignificant, redundant and empty variables
	drop team_code screen_1dist_name screen_1block_name screen_1town_name screen_1pincode metainstanceid simid subscriberid _merge
	
	// Renaming variables
	rename district _district_name
	rename pss _pss_name
	rename feeder _feeder_name
	rename area _area_name
	rename village_id1 _district_id
	rename village_id2 _pss_id
	rename village_id3 _feeder_id
	rename village_id4 _area_id
	rename areaid _area_id_complete
	rename endtime _survey_end_datetime
	rename parent_key _survey_parent_id
	rename starttime _survey_start_datetime
	rename submissiondate _survey_submission_datetime
	rename deviceid _survey_device_id
	rename scr_1supervis_name _supervisor_name
	rename scr_1supervis_code _supervisor_code
	rename dt_acc dt_gps_accuracy
	rename dt_lat dt_gps_latitude
	rename dt_long dt_gps_longitude
	rename dt_alt dt_gps_altitude
	rename dt_name dt_landmark
	rename pos dt_pos
	rename areatype _area_type
	
	// Labelling variables
	label variable _district_name "District name"
	label variable _pss_name "PSS name"
	label variable _feeder_name "Feeder name"
	label variable _area_id_complete "Complete area ID"
	label variable _area_name "Area name"
	label variable _district_id "District ID"
	label variable _pss_id "PSS ID"
	label variable _feeder_id "Feeder ID"
	label variable _area_id "Area ID"
	label variable _survey_parent_id "Parent key"
	label variable _survey_submission_datetime "Survey submission date and time combined"
	label variable _survey_start_datetime "Survey start date andd time combined"
	label variable _survey_end_datetime "Survey end date andd time combined"
	label variable _survey_device_id "Tablet ID"
	label variable _supervisor_name "Supervisor name"
	label variable _supervisor_code "Supervisor code"
	label variable dt_code "Distribution transformer 11 digit unique code"
	label variable dt_gps_latitude "Distribution transformer GPS latitude reading"
	label variable dt_gps_longitude "Distribution transformer GPS longitude reading"
	label variable dt_gps_altitude "Distribution transformer GPS altitude reading"
	label variable dt_gps_accuracy "Distribution transformer GPS reading precision in meters"
	label variable dt_landmark "Distribution transformer local landmark details"
	label variable dt_pos "Distribution transformer position among different DTs of same area"

	
* RENAMING DISTRICT, PSS & FEEDER TO MATCH IMPLEMENTATION DATA

	// Renaming District
	replace _district_name="Saran" if _district_name=="CHAPRA"
	replace _district_name="Purnea" if _district_name=="PURNIA"
	replace _district_name=upper(_district_name)
	
	// Renaming PSS
	replace _pss_name="A2Z " if _pss_name=="A2Z"
	replace _pss_name="AKHGAW" if _pss_name=="AKHGAW"
	replace _pss_name="BARHARA" if _pss_name=="BARHARA"
	replace _pss_name="BIHIYA" if _pss_name=="BIHIYA"
	replace _pss_name="GARHANI" if _pss_name=="GARHANI"
	replace _pss_name="JAGDISHPUR" if _pss_name=="JAGDISHPUR"
	replace _pss_name="KOILWAR" if _pss_name=="KOILWAR"
	replace _pss_name="PIRO" if _pss_name=="PIRO"
	replace _pss_name="SAHAR" if _pss_name=="SAHAR"
	replace _pss_name="SAHPUR" if _pss_name=="SAHPUR"
	replace _pss_name="SANDESH" if _pss_name=="SANDESH"
	replace _pss_name="SARAIYA" if _pss_name=="SARAIYA"
	replace _pss_name="TARARI" if _pss_name=="TARARI"
	replace _pss_name="BRAHMPUR" if _pss_name=="BRAHMPUR"
	replace _pss_name="BUXAR TOWN" if _pss_name=="BUXAR TOWN"
	replace _pss_name="CHHOTKA DHANKAICH" if _pss_name=="CHHOTKA DHANKAICH"
	replace _pss_name="CHOUSA" if _pss_name=="CHOUSA"
	replace _pss_name="DUMRAON" if _pss_name=="DUMRAON"
	replace _pss_name="EKRASI" if _pss_name=="EKRASI"
	replace _pss_name="INDUSTRIAL" if _pss_name=="INDRUSTRIAL"
	replace _pss_name="ITHARI" if _pss_name=="ITHARI"
	replace _pss_name="MURAR" if _pss_name=="MURAR"
	replace _pss_name="NAWANAGAR" if _pss_name=="NAWANAGAR"
	replace _pss_name="NUWAON" if _pss_name=="NUWAON"
	replace _pss_name="PRUSHTOMPUR" if _pss_name=="PRUSHTOMPUR"
	replace _pss_name="SIMRI" if _pss_name=="SIMRI"
	replace _pss_name="Amnour" if _pss_name=="AMNOUR"
	replace _pss_name="Baniyapur" if _pss_name=="BANIYAPUR"
	replace _pss_name="Dariyapur" if _pss_name=="DARIYAPUR"
	replace _pss_name="Dighwara" if _pss_name=="DIGHWARA"
	replace _pss_name="Ekma" if _pss_name=="EKMA"
	replace _pss_name="Garakha" if _pss_name=="GARAKHA"
	replace _pss_name="Lahlladpur" if _pss_name=="LAHLADPUR"
	replace _pss_name="Manjhi" if _pss_name=="MANJHI"
	replace _pss_name="Marhaura" if _pss_name=="MARHORA"
	replace _pss_name="Masakrakh" if _pss_name=="MASRAKH"
	replace _pss_name="Panapur" if _pss_name=="PANAPUR"
	replace _pss_name="Parbhunath Nagar" if _pss_name=="PARBHUNATH NAGAR"
	replace _pss_name="Parsa" if _pss_name=="PARSA"
	replace _pss_name="Setalpur" if _pss_name=="SETALPUR"
	replace _pss_name="Sonpur" if _pss_name=="SONPUR"
	replace _pss_name="Taraiya" if _pss_name=="TARAIYA"
	replace _pss_name="Telpa" if _pss_name=="TELPA"
	replace _pss_name="Barsoi" if _pss_name=="BARSOI"
	replace _pss_name="Falka" if _pss_name=="FALKA"
	replace _pss_name="Korha" if _pss_name=="KORHA"
	replace _pss_name="Kursela" if _pss_name=="KURSELA"
	replace _pss_name="Mirchaibari" if _pss_name=="MIRCHAIBARI"
	replace _pss_name="Pranpur" if _pss_name=="PRANPUR"
	replace _pss_name="Sonaili" if _pss_name=="SONAILI"
	replace _pss_name="Amour" if _pss_name=="AMOUR"
	replace _pss_name="Baisa" if _pss_name=="BAISA"
	replace _pss_name="Banmankhi" if _pss_name=="BANMANKHI"
	replace _pss_name="Belgacchi" if _pss_name=="BELGACHHI"
	replace _pss_name="Dalkola" if _pss_name=="DALKOLHA"
	replace _pss_name="Dargah" if _pss_name=="DARGAH"
	replace _pss_name="Jalalgarh" if _pss_name=="JALALGARH"
	replace _pss_name="Maranga" if _pss_name=="MARANGA"
	replace _pss_name="Mirganj (Purnea)" if _pss_name=="MIRGANJ"
	replace _pss_name="Sondeep" if _pss_name=="SONDEEP"
	replace _pss_name="Zero Mile" if _pss_name=="ZERO MILE"
	replace _pss_name="Barhariya" if _pss_name=="BARHARIYA"
	replace _pss_name="Basantpur" if _pss_name=="BASANTPUR"
	replace _pss_name="Chainpur" if _pss_name=="CHAINPUR"
	replace _pss_name="Goriyakothi" if _pss_name=="GORIYAKOTHI"
	replace _pss_name="Mahrajganj" if _pss_name=="MAHARAJGANJ"
	replace _pss_name="Mairwa" if _pss_name=="MAIRWA"
	replace _pss_name="Panchrukhi" if _pss_name=="PANCHRUKHI"
	replace _pss_name="Raghunathpur" if _pss_name=="RAGHUNATHPUR"
	replace _pss_name="Siwan" if _pss_name=="SIWAN"
	replace _pss_name="Srinagar" if _pss_name=="SRINAGAR"
	replace _pss_name="Ahilaya Asthan" if _pss_name=="AHILYA ASTHAN"
	replace _pss_name="Anar" if _pss_name=="ANAR"
	replace _pss_name="Baheri" if _pss_name=="BAHERI"
	replace _pss_name="Gangwara" if _pss_name=="GANGWARA"
	replace _pss_name="Jail (Lahariasarai)" if _pss_name=="JAIL (LAHERIYASARAI)"
	replace _pss_name="Poria" if _pss_name=="PORIYA"
	replace _pss_name="Sanahpurdih" if _pss_name=="SANAHPURDIH"
	replace _pss_name="Dariyapur" if _pss_name=="DARIYAPUR"
	replace _pss_name="Dhanarua" if _pss_name=="DHANARUA"
	replace _pss_name="Bakhtiyarpur" if _pss_name=="BAKHTIYARPUR"
	replace _pss_name="Barh" if _pss_name=="BARH"
	replace _pss_name="Belchi" if _pss_name=="BELCHI"
	replace _pss_name="Bhusaula" if _pss_name=="BHUSAULA"
	replace _pss_name="Bihari Bigha" if _pss_name=="BIHARI BIGHA"
	replace _pss_name="Daniyama" if _pss_name=="DANIYAMA"
	replace _pss_name="Fatuha" if _pss_name=="FATUHA"
	replace _pss_name="Khusrupur" if _pss_name=="FATUHA RURAL (KHUSRUPUR)"
	replace _pss_name="Hathidah" if _pss_name=="HATHIDAH"
	replace _pss_name="Mokama" if _pss_name=="MOKAMA"
	replace _pss_name="Neora" if _pss_name=="NEORA"
	replace _pss_name="Pandarak" if _pss_name=="PANDARAK"
	replace _pss_name="Sabalpur" if _pss_name=="SABALPUR"
	replace _pss_name="Airforce" if _pss_name=="AIRFORCE"
	replace _pss_name="Bihta Old" if _pss_name=="BIHTA OLD"
	replace _pss_name="Bikram" if _pss_name=="BIKRAM"
	replace _pss_name="Kanpa" if _pss_name=="KANPA"
	replace _pss_name="Kuda Nawada" if _pss_name=="KUDA NAWADA"
	replace _pss_name="Lala Bhadsara" if _pss_name=="LALA BHADSARA"
	replace _pss_name="MANER" if _pss_name=="MANER"
	replace _pss_name="Masaurhi New" if _pss_name=="MASAURHI NEW"
	replace _pss_name="Masaurhi Old" if _pss_name=="MASAURHI OLD"
	replace _pss_name="Naubatpur" if _pss_name=="NAUBATPUR"
	replace _pss_name="Paliganj" if _pss_name=="PALIGANJ"
	replace _pss_name="Pareo" if _pss_name=="PAREO"
	replace _pss_name="Sampatchak" if _pss_name=="SAMPATCHAK"
	replace _pss_name="Sherpur" if _pss_name=="SHERPUR"
	replace _pss_name=upper(_pss_name)
	
	// Renaming Feeder
	replace _feeder_name="ASNI" if _feeder_name=="ASNI"
	replace _feeder_name="KARISATH" if _feeder_name=="KARISATH"
	replace _feeder_name="UDWANT NAGAR" if _feeder_name=="UDWANT NAGAR"
	replace _feeder_name="FEDER N0-1" if _feeder_name=="FEDER N0-1"
	replace _feeder_name="FEDER N0-2" if _feeder_name=="FEDER N0-2"
	replace _feeder_name="FEDER N0-3" if _feeder_name=="FEDER N0-3"
	replace _feeder_name="FEDER N0-4" if _feeder_name=="FEDER N0-4"
	replace _feeder_name="Feeder-1" if _feeder_name=="FEEDER-1"
	replace _feeder_name="Feeder-2" if _feeder_name=="FEEDER-2"
	replace _feeder_name="Feeder-3" if _feeder_name=="FEEDER-3"
	replace _feeder_name="Feeder-4" if _feeder_name=="FEEDER-4"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="T0WN" if _feeder_name=="T0WN"
	replace _feeder_name="AGIYAW" if _feeder_name=="AGIYAW"
	replace _feeder_name="Charpokhari" if _feeder_name=="CHARPOKHARI"
	replace _feeder_name="Garhani" if _feeder_name=="GARHANI"
	replace _feeder_name="Kasap" if _feeder_name=="KASAP"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="Town" if _feeder_name=="TOWN"
	replace _feeder_name="Chandi" if _feeder_name=="CHANDI"
	replace _feeder_name="Dhandiha" if _feeder_name=="DHANDIHA"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="Urban" if _feeder_name=="URBAN"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="T0WN" if _feeder_name=="T0WN"
	replace _feeder_name="AGIYAW" if _feeder_name=="AGIYAW"
	replace _feeder_name="BAHUWARA" if _feeder_name=="BAHUWARA"
	replace _feeder_name="KHAIRA" if _feeder_name=="KHAIRA"
	replace _feeder_name="SAHAR" if _feeder_name=="SAHAR"
	replace _feeder_name="Banahi" if _feeder_name=="BANAHI"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="Town" if _feeder_name=="TOWN"
	replace _feeder_name="Rural" if _feeder_name=="RURAL"
	replace _feeder_name="Town" if _feeder_name=="TOWN"
	replace _feeder_name="Dhobaha" if _feeder_name=="DHOBAHA"
	replace _feeder_name="SARAIYA" if _feeder_name=="SARAIYA"
	replace _feeder_name="Bihta" if _feeder_name=="BIHITA"
	replace _feeder_name="Chakiya" if _feeder_name=="CHAKIYA"
	replace _feeder_name="KARATH" if _feeder_name=="KARATH"
	replace _feeder_name="N0NAR" if _feeder_name=="N0NAR"
	replace _feeder_name="BRAHMPUR" if _feeder_name=="BRAHMPUR"
	replace _feeder_name="RAGHUNATHPUR" if _feeder_name=="RAGHUNATHPUR"
	replace _feeder_name="RAJPUR" if _feeder_name=="RAJPUR"
	replace _feeder_name="RURAL" if _feeder_name=="RURAL"
	replace _feeder_name="D.K.COLLAGE" if _feeder_name=="D.K.COLLAGE"
	replace _feeder_name="DHANKAICH" if _feeder_name=="DHANKAICH"
	replace _feeder_name="CHOUSA" if _feeder_name=="CHOUSA"
	replace _feeder_name="GOLA" if _feeder_name=="GOLA"
	replace _feeder_name="BHOJPUR" if _feeder_name=="BHOJPUR"
	replace _feeder_name="DUMRAON TOWN" if _feeder_name=="DUMRAON TOWN"
	replace _feeder_name="RURAL" if _feeder_name=="RURAL"
	replace _feeder_name="VARUNA" if _feeder_name=="VARUNA"
	replace _feeder_name="EKRASI" if _feeder_name=="EKRASI"
	replace _feeder_name="MURAR II" if _feeder_name=="MURAR II"
	replace _feeder_name="DALSAGAR" if _feeder_name=="DALSAGAR"
	replace _feeder_name="DHANSOI" if _feeder_name=="DHANSOI"
	replace _feeder_name="ITHARI" if _feeder_name=="ITHARI"
	replace _feeder_name="KHOKHA" if _feeder_name=="KHOKHA"
	replace _feeder_name="MURAR" if _feeder_name=="MURAR"
	replace _feeder_name="AATHER" if _feeder_name=="AATHER"
	replace _feeder_name="NARVODAY" if _feeder_name=="NARVODAY"
	replace _feeder_name="NAWANAGAR" if _feeder_name=="NAWANAGAR"
	replace _feeder_name="RANA" if _feeder_name=="RANA"
	replace _feeder_name="BRAHMPUR" if _feeder_name=="BRAHMPUR"
	replace _feeder_name="KATHAR" if _feeder_name=="KATHAR"
	replace _feeder_name="NUWAON" if _feeder_name=="NUWAON"
	replace _feeder_name="DHANSOI" if _feeder_name=="DHANSOI"
	replace _feeder_name="INDOR" if _feeder_name=="INDOR"
	replace _feeder_name="RAJPUR" if _feeder_name=="RAJPUR"
	replace _feeder_name="UNWASH" if _feeder_name=="UNWASH"
	replace _feeder_name="DULLAHPUR" if _feeder_name=="DULLAHPUR"
	replace _feeder_name="PADRI" if _feeder_name=="PADRI"
	replace _feeder_name="SIMRI" if _feeder_name=="SIMRI"
	replace _feeder_name="Amnour (Amnour)" if _feeder_name=="AMNOUR"
	replace _feeder_name="Beldi (Amnour)" if _feeder_name=="BELDI"
	replace _feeder_name="Maker" if _feeder_name=="MAKER"
	replace _feeder_name="Parshurampur" if _feeder_name=="PARSHURAMPUR"
	replace _feeder_name="Banoyapur" if _feeder_name=="BANOYAPUR"
	replace _feeder_name="Jantabazar (Baniyapur) / Sahajitpur" if _feeder_name=="JANTABAZAR (BANIYAPUR) / SAHAJITPUR"
	replace _feeder_name="Nagara" if _feeder_name=="NAGARA"
	replace _feeder_name="Dariyapu 2 / Devati" if _feeder_name=="DARIYAPU 2 / DEVATI"
	replace _feeder_name="Dariyapu 3 / Sundarpur" if _feeder_name=="DARIYAPU 3 / SUNDARPUR"
	replace _feeder_name="Dariyapu 4 / Dariyapur" if _feeder_name=="DARIYAPU 4 / DARIYAPUR"
	replace _feeder_name="Dariyapur 1 / Darihara / Darani" if _feeder_name=="DARIYAPUR 1 / DARIHARA / DARANI"
	replace _feeder_name="Dighwara (Dighwara)" if _feeder_name=="DIGHWARA"
	replace _feeder_name="Matihan" if _feeder_name=="MATIHAN"
	replace _feeder_name="Daudpur" if _feeder_name=="DAUDPUR"
	replace _feeder_name="Ekma" if _feeder_name=="EKMA"
	replace _feeder_name="Basant" if _feeder_name=="BASANT"
	replace _feeder_name="Garkha" if _feeder_name=="GARKHA"
	replace _feeder_name="Basahi" if _feeder_name=="BASAHI"
	replace _feeder_name="Jantabazar (Lahlladpur)" if _feeder_name=="JANTABAZAR (LAHLLADPUR)"
	replace _feeder_name="Iliyaspur" if _feeder_name=="ILIYASPUR"
	replace _feeder_name="Tajpur (Manjhi)" if _feeder_name=="TAJPUR (MANJHI)"
	replace _feeder_name="Amnaur (Marhaura)" if _feeder_name=="AMNAUR"
	replace _feeder_name="Isuapur" if _feeder_name=="ISUAPUR"
	replace _feeder_name="Marhuwara Town" if _feeder_name=="MARHUWARA TOWN"
	replace _feeder_name="Sivganj" if _feeder_name=="SIVGANJ"
	replace _feeder_name="Hanumanganj" if _feeder_name=="HANUMANGANJ"
	replace _feeder_name="Masarakh Rural" if _feeder_name=="MASARAKH RURAL"
	replace _feeder_name="Masarakh Urban" if _feeder_name=="MASARAKH URBAN"
	replace _feeder_name="Dubauli" if _feeder_name=="DUBAULI"
	replace _feeder_name="Panapur" if _feeder_name=="PANAPUR"
	replace _feeder_name="Totaha" if _feeder_name=="TOTAHA"
	replace _feeder_name="Khaira" if _feeder_name=="KHAIRA"
	replace _feeder_name="Naini" if _feeder_name=="NANI"
	replace _feeder_name="Anjani" if _feeder_name=="ANJANI"
	replace _feeder_name="Mirzapur" if _feeder_name=="MIRZAPUR"
	replace _feeder_name="Parsa" if _feeder_name=="PARSA"
	replace _feeder_name="Manpur" if _feeder_name=="MANPUR"
	replace _feeder_name="Setalpur" if _feeder_name=="SETALPUR"
	replace _feeder_name="Setalpur Kothi" if _feeder_name=="SETALPUR KOTHI"
	replace _feeder_name="Kharikha" if _feeder_name=="KHARIKHA"
	replace _feeder_name="Mela" if _feeder_name=="MELA"
	replace _feeder_name="Nayagaon" if _feeder_name=="NAYAGAON"
	replace _feeder_name="Ragistry" if _feeder_name=="RAGISTRY"
	replace _feeder_name="Taraiya" if _feeder_name=="TARAIYA"
	replace _feeder_name="Taraiya 1" if _feeder_name=="TARAIYA 1"
	replace _feeder_name="Taraiya 2" if _feeder_name=="TARAIYA 2"
	replace _feeder_name="Beldi" if _feeder_name=="BELDI"
	replace _feeder_name="Dighwara / Dariganj" if _feeder_name=="DARIGANJ"
	replace _feeder_name="Abadpur" if _feeder_name=="ABADPUR R"
	replace _feeder_name="Barsoi" if _feeder_name=="BARSOI U"
	replace _feeder_name="Railway (Barsoi)" if _feeder_name=="RAILWAY BARSOI U"
	replace _feeder_name="Salmari" if _feeder_name=="SALMARI R"
	replace _feeder_name="Sudhani" if _feeder_name=="SUDHANI R"
	replace _feeder_name="Bhangha" if _feeder_name=="BHANGHA U"
	replace _feeder_name="Bharsia" if _feeder_name=="BHARSIA R"
	replace _feeder_name="Falka Bazar" if _feeder_name=="FALKA BAZAR R"
	replace _feeder_name="Dedicated STW" if _feeder_name=="DEDICATED STW U"
	replace _feeder_name="Gerabari Bazar" if _feeder_name=="GERABARI BAZAR U"
	replace _feeder_name="Harda (Korha)" if _feeder_name=="HARDA (KORHA) R"
	replace _feeder_name="Kolasi" if _feeder_name=="KOLASI R"
	replace _feeder_name="Semapur" if _feeder_name=="SEMAPUR R"
	replace _feeder_name="Barari (Kursela)" if _feeder_name=="BARARI R"
	replace _feeder_name="Kursela" if _feeder_name=="KURSELA M"
	replace _feeder_name="Hasanganj" if _feeder_name=="HASANGANJ R"
	replace _feeder_name="Manihari" if _feeder_name=="MANIHARI R"
	replace _feeder_name="Bastaul" if _feeder_name=="BASTAUL R"
	replace _feeder_name="PHED Pranpur" if _feeder_name=="PHED PRANPURU"
	replace _feeder_name="Pranpur" if _feeder_name=="PRANPUR U"
	replace _feeder_name="Roshna" if _feeder_name=="ROSHNA R"
	replace _feeder_name="Bhogaon" if _feeder_name=="BHOGAON R"
	replace _feeder_name="Kumhari" if _feeder_name=="KUMHARI R"
	replace _feeder_name="Sonaili (Sonaili)" if _feeder_name=="SONAILI U"
	replace _feeder_name="Amour Rural" if _feeder_name=="AMOUR RURAL"
	replace _feeder_name="Amour Town" if _feeder_name=="AMOUR TOWN"
	replace _feeder_name="Gerwa" if _feeder_name=="GERWA"
	replace _feeder_name="Routa" if _feeder_name=="RAOUTA"
	replace _feeder_name="Amanpure" if _feeder_name=="AMANPURE"
	replace _feeder_name="Kharif" if _feeder_name=="KHARIF"
	replace _feeder_name="Sinabari" if _feeder_name=="SINABARI"
	replace _feeder_name="Banmankhi" if _feeder_name=="BANMANKHI"
	replace _feeder_name="Jankinagar" if _feeder_name=="JANKINAGAR"
	replace _feeder_name="Khajuri" if _feeder_name=="KHAJURI"
	replace _feeder_name="Rasadh" if _feeder_name=="RASADH"
	replace _feeder_name="Baisbaily" if _feeder_name=="BAISBAILY"
	replace _feeder_name="Baisee" if _feeder_name=="BAISI"
	replace _feeder_name="Belgacchi" if _feeder_name=="BELGACHHI"
	replace _feeder_name="Barsoyi" if _feeder_name=="BARSOI"
	replace _feeder_name="Milikpur" if _feeder_name=="MILIKPUR"
	replace _feeder_name="Bela (Dargah)" if _feeder_name=="BELA"
	replace _feeder_name="Dargah" if _feeder_name=="DARGAH"
	replace _feeder_name="Jhalari (Dargah)" if _feeder_name=="JHALARI"
	replace _feeder_name="Rupauli" if _feeder_name=="RUPAULI"
	replace _feeder_name="Garhbanaily" if _feeder_name=="GARHBANAILY"
	replace _feeder_name="Jalalgarh" if _feeder_name=="JALALGARH"
	replace _feeder_name="Kasba" if _feeder_name=="KASBA"
	replace _feeder_name="Srinagar (Jalalgarh)" if _feeder_name=="SRINAGAR"
	replace _feeder_name="Champanagar" if _feeder_name=="CHAMPANAGAR"
	replace _feeder_name="Harda (Maranga)" if _feeder_name=="HARDA"
	replace _feeder_name="Sonaily (Maranga)" if _feeder_name=="SONAILY"
	replace _feeder_name="Baheliya Asthan" if _feeder_name=="BAHELIYA ASTHAN"
	replace _feeder_name="Champawati" if _feeder_name=="CHAMPAWATI"
	replace _feeder_name="Chandwa" if _feeder_name=="CHANDWA"
	replace _feeder_name="Dhamdaha" if _feeder_name=="DHAMDAHA"
	replace _feeder_name="Mirganj (Purnea)" if _feeder_name=="MIRGANJ"
	replace _feeder_name="Bhawanipur" if _feeder_name=="BHAWANIPUR"
	replace _feeder_name="Jabey" if _feeder_name=="JABEY"
	replace _feeder_name="Sondeep" if _feeder_name=="SONDEEP"
	replace _feeder_name="Dagarua" if _feeder_name=="DAGARUA"
	replace _feeder_name="Zero Mile" if _feeder_name=="ZERO MILE"
	replace _feeder_name="Chari" if _feeder_name=="CHARI"
	replace _feeder_name="Jamo" if _feeder_name=="JAMO"
	replace _feeder_name="Lakri" if _feeder_name=="LAKRI"
	replace _feeder_name="Basntpur" if _feeder_name=="BASANTPUR"
	replace _feeder_name="Bhagawanpur (Basantpur)" if _feeder_name=="BHAGAWANPUR (BASANTPUR)"
	replace _feeder_name="Bhopatpur" if _feeder_name=="BHOPATPUR"
	replace _feeder_name="Gopalpur (Basantpur)" if _feeder_name=="GOPALPUR (BASANTPUR)"
	replace _feeder_name="Barari (Chainpur)" if _feeder_name=="BARARI"
	replace _feeder_name="Hasanpura (Chainpur)" if _feeder_name=="HASANPURA (CHAINPUR)"
	replace _feeder_name="Sisawan" if _feeder_name=="SISAWAN"
	replace _feeder_name="Tari" if _feeder_name=="TARI"
	replace _feeder_name="Dumari" if _feeder_name=="DUMARI"
	replace _feeder_name="Goriyakopthi" if _feeder_name=="GORIYAKOTHI"
	replace _feeder_name="Musatafabad" if _feeder_name=="MUSATAFABAD"
	replace _feeder_name="Basantpur (Maharganj)" if _feeder_name=="BASANTPUR (MAHARGANJ)"
	replace _feeder_name="Dharaundra" if _feeder_name=="DHARAUNDRA"
	replace _feeder_name="Maharajganj" if _feeder_name=="MAHARAJGANJ"
	replace _feeder_name="Tarwara (Mahrajganj)" if _feeder_name=="TARWARA (MAHRAJGANJ)"
	replace _feeder_name="Darauli" if _feeder_name=="DARAULI"
	replace _feeder_name="Guthani" if _feeder_name=="GUTHANI"
	replace _feeder_name="Mairwa" if _feeder_name=="MAIRWA"
	replace _feeder_name="Titara" if _feeder_name=="TITARA"
	replace _feeder_name="Hasanpura (Panchrukhi)" if _feeder_name=="HASANPURA (PANCHRUKHI)"
	replace _feeder_name="Panchrukhi" if _feeder_name=="PANCHRUKHI"
	replace _feeder_name="Talkathu" if _feeder_name=="TALKATHU"
	replace _feeder_name="Tarwara (Panchrukhi)" if _feeder_name=="TARWARA (PANCHRUKHI)"
	replace _feeder_name="Amndar" if _feeder_name=="AMNDAR"
	replace _feeder_name="Raghunathpur" if _feeder_name=="RAGHUNATHPUR"
	replace _feeder_name="Andardhal / Konhara" if _feeder_name=="ANDARDHAL / KONHARA"
	replace _feeder_name="Barhariya (Siwan)" if _feeder_name=="BARHARIYA (SIWAN)"
	replace _feeder_name="Dhanauti" if _feeder_name=="DHANAUTI"
	replace _feeder_name="Jeradei" if _feeder_name=="JERADEI"
	replace _feeder_name="Kamtol" if _feeder_name=="KAMTOL"
	replace _feeder_name="Tekrar" if _feeder_name=="TEKRAR"
	replace _feeder_name="Anar" if _feeder_name=="ANAR"
	replace _feeder_name="Baheri (Anar)" if _feeder_name=="BAHERI"
	replace _feeder_name="Chandanpatti" if _feeder_name=="CHANDANPATTI"
	replace _feeder_name="Hayaghat" if _feeder_name=="HAYAGHAT"
	replace _feeder_name="Kapchahi" if _feeder_name=="KAPCHAHI"
	replace _feeder_name="Baheri" if _feeder_name=="BAHERI U"
	replace _feeder_name="Khangraitha" if _feeder_name=="KHANGRAITHA R"
	replace _feeder_name="Aerodram" if _feeder_name=="AERODRAM U"
	replace _feeder_name="Garharia" if _feeder_name=="GARHARIA U"
	replace _feeder_name="Kamtaul (Gangwara)" if _feeder_name=="KAMTAUL (GANGWARA) R"
	replace _feeder_name="Loam" if _feeder_name=="LOAM R"
	replace _feeder_name="Mithila" if _feeder_name=="MITHILA M"
	replace _feeder_name="Ramnagar" if _feeder_name=="RAMNAGAR R"
	replace _feeder_name="Shovan" if _feeder_name=="SHOVAN R"
	replace _feeder_name="Ekmi" if _feeder_name=="EKMI R"
	replace _feeder_name="Rural Jail" if _feeder_name=="RURAL JAIL M"
	replace _feeder_name="Bishanpur" if _feeder_name=="BISHANPUR R"
	replace _feeder_name="Dilahi" if _feeder_name=="DILAHI R"
	replace _feeder_name="Bharwara" if _feeder_name=="BHARWARA"
	replace _feeder_name="Jalley" if _feeder_name=="JALLEY"
	replace _feeder_name="Singhwara" if _feeder_name=="SINGHWARA"
	replace _feeder_name="Gadauli" if _feeder_name=="BEDOULI"
	replace _feeder_name="Dariyapur" if _feeder_name=="DARIYAPUR"
	replace _feeder_name="Bansbigaha" if _feeder_name=="BANSBIGAHA"
	replace _feeder_name="Deokuli (Town)" if _feeder_name=="DEOKULI (TOWN)"
	replace _feeder_name="Kolhachak" if _feeder_name=="KOLHACHAK"
	replace _feeder_name="Bakhtiyarpur" if _feeder_name=="BAKHTIYARPUR"
	replace _feeder_name="Duplicate (Bakhtiyarpur)" if _feeder_name=="DUPLICATE"
	replace _feeder_name="Rural (Bakhtiyarpur)" if _feeder_name=="RURAL"
	replace _feeder_name="Telmar" if _feeder_name=="TELMAR"
	replace _feeder_name="Malahi" if _feeder_name=="MALAHI"
	replace _feeder_name="Pandarakh" if _feeder_name=="PANDARAKH"
	replace _feeder_name="PHED (Barh)" if _feeder_name=="PHED"
	replace _feeder_name="Rural (Barh)" if _feeder_name=="RURAL"
	replace _feeder_name="Town (Barh)" if _feeder_name=="TOWN"
	replace _feeder_name="Ekdanga" if _feeder_name=="EKDANGA"
	replace _feeder_name="Gogiyari" if _feeder_name=="GOGIYARI"
	replace _feeder_name="Gopalpur" if _feeder_name=="GOPALPUR"
	replace _feeder_name="Mankoura" if _feeder_name=="MANKOURA"
	replace _feeder_name="Babhanpura" if _feeder_name=="BABHANPURA"
	replace _feeder_name="Hinduni" if _feeder_name=="HINDUNI"
	replace _feeder_name="Janipur" if _feeder_name=="JANIPUR"
	replace _feeder_name="Chaturbhujpur" if _feeder_name=="CHATURBHUJPUR"
	replace _feeder_name="Manikpur" if _feeder_name=="MANIKPUR"
	replace _feeder_name="Pokharpur" if _feeder_name=="POKHARPUR"
	replace _feeder_name="Rice (Bihari Bigha)" if _feeder_name=="RICE"
	replace _feeder_name="Daniyawa" if _feeder_name=="DANIYAWA"
	replace _feeder_name="Machariyawa" if _feeder_name=="MACHARIYAWA"
	replace _feeder_name="Budhuchak" if _feeder_name=="BUDHUCHAK"
	replace _feeder_name="Industrial (Fatuha)" if _feeder_name=="INDUSTRIAL"
	replace _feeder_name="Khusrupur (Fatuha)" if _feeder_name=="KHUSRUPUR"
	replace _feeder_name="Radio (Fatuha)" if _feeder_name=="RADIO"
	replace _feeder_name="Rural (Fatuha)" if _feeder_name=="RURAL"
	replace _feeder_name="Station (Fatuha)" if _feeder_name=="STATION"
	replace _feeder_name="Bakhtiyarpur" if _feeder_name=="BAKHTIYARPUR"
	replace _feeder_name="Khusrupur (Khusrupur)" if _feeder_name=="KHUSRUPUR"
	replace _feeder_name="Bata" if _feeder_name=="BATA"
	replace _feeder_name="Hathidah" if _feeder_name=="HATHIDAH"
	replace _feeder_name="Maranchi New" if _feeder_name=="MARACHI NEW"
	replace _feeder_name="Maranchi Old" if _feeder_name=="MARACHI OLD"
	replace _feeder_name="NTPC (Mokama)" if _feeder_name=="NTPC"
	replace _feeder_name="PHED (Mokama)" if _feeder_name=="PHED"
	replace _feeder_name="Road Side (Mokama)" if _feeder_name=="ROAD SIDE"
	replace _feeder_name="Town 1 (Mokama)" if _feeder_name=="TOWN 1"
	replace _feeder_name="Town 2 (Mokama)" if _feeder_name=="TOWN 2"
	replace _feeder_name="Co-Operative (Neora)" if _feeder_name=="CO-OPERATIVE"
	replace _feeder_name="Neora" if _feeder_name=="NEORA"
	replace _feeder_name="Pandarak" if _feeder_name=="PANDARAK"
	replace _feeder_name="Kothiya" if _feeder_name=="KOTHIYA"
	replace _feeder_name="Raibagh" if _feeder_name=="RAIBAGH"
	replace _feeder_name="Rural (Airforce)" if _feeder_name=="RURAL"
	replace _feeder_name="VCL (Airforce)" if _feeder_name=="VCL"
	replace _feeder_name="Bihta" if _feeder_name=="BIHTA"
	replace _feeder_name="CPWD (Bihta Old)" if _feeder_name=="CPWD"
	replace _feeder_name="Jeenpura" if _feeder_name=="JEENPURA"
	replace _feeder_name="Maner" if _feeder_name=="MANER"
	replace _feeder_name="Naubatpur (Bihta Old)" if _feeder_name=="NAUBATPUR"
	replace _feeder_name="Akhtiyarpur" if _feeder_name=="AKHTIYARPUR"
	replace _feeder_name="Bikram (Bikram)" if _feeder_name=="BIKRAM"
	replace _feeder_name="DinaBigha" if _feeder_name=="DINABIGHA"
	replace _feeder_name="Barah" if _feeder_name=="BARAH"
	replace _feeder_name="Bikram (Kanpa)" if _feeder_name=="BIKARAM"
	replace _feeder_name="Kanpa" if _feeder_name=="KANPA"
	replace _feeder_name="Co-Operative (Kuda Nawada)" if _feeder_name=="CO-OPERATIVE"
	replace _feeder_name="Pothi" if _feeder_name=="POTHI"
	replace _feeder_name="Punpun Bazaar" if _feeder_name=="PUNPUN BAZAAR"
	replace _feeder_name="Railway West (Kuda Nawada)" if _feeder_name=="RAILWAY WEST"
	replace _feeder_name="Bikram (Lala Bhadsara)" if _feeder_name=="BIKRAM"
	replace _feeder_name="Dulhin Bazaar" if _feeder_name=="DULHIN BAZAAR"
	replace _feeder_name="Lalbhadsara" if _feeder_name=="LALBHADSARA"
	replace _feeder_name="Masaurhi" if _feeder_name=="MASAURHI"
	replace _feeder_name="RAMBAGH" if _feeder_name=="RAMBAGH"
	replace _feeder_name="RURAL (MANER)" if _feeder_name=="RURAL"
	replace _feeder_name="SIMARI" if _feeder_name=="SIMARI"
	replace _feeder_name="TOWN (MANER)" if _feeder_name=="TOWN"
	replace _feeder_name="Chapour" if _feeder_name=="CHAPOUR"
	replace _feeder_name="Deowaria" if _feeder_name=="DEOWARIA"
	replace _feeder_name="Town (Masaurhi New)" if _feeder_name=="TOWN"
	replace _feeder_name="Dhanarua" if _feeder_name=="DHANARUA"
	replace _feeder_name="Nadaul" if _feeder_name=="NADAUL"
	replace _feeder_name="Nadwa" if _feeder_name=="NADWA"
	replace _feeder_name="Jaitipur" if _feeder_name=="JAITIPUR"
	replace _feeder_name="Naubatpur (Naubatpur)" if _feeder_name=="NAUBATPUR"
	replace _feeder_name="Banauli" if _feeder_name=="BANAULI"
	replace _feeder_name="Mahabalipur" if _feeder_name=="MAHABALIPUR"
	replace _feeder_name="Paliganj" if _feeder_name=="PALIGANJ"
	replace _feeder_name="Shigori" if _feeder_name=="SHIGORI"
	replace _feeder_name="Lai (Pareo)" if _feeder_name=="LAI"
	replace _feeder_name="Pareo" if _feeder_name=="PAREO"
	replace _feeder_name="Gaurichak Duplicate" if _feeder_name=="GAURICHAK DUPLICATE"
	replace _feeder_name="Gaurichak Main" if _feeder_name=="GAURICHAK MAIN"
	replace _feeder_name="Saudih" if _feeder_name=="SAUDIH"
	replace _feeder_name="Sono Gopalpur" if _feeder_name=="SONO GOPALPUR"
	replace _feeder_name="Byapur" if _feeder_name=="BYAPUR"
	replace _feeder_name="Sherpur" if _feeder_name=="SHERPUR"
	replace _feeder_name=upper(_feeder_name)
	
	order _all, sequential

	
* SAVING WORKING DATA AND CODEBOOK

	cd "`WORKING_DATA'"
	save CUMULATIVE_DT_VIL_16May2015_WORKING, replace
	log using area_dt_survey_codebook.txt, text
	codebook
	log close
	